[phases.setup]
commands = [
  "pip install --upgrade pip"
]

[phases.install]
commands = [
  "pip install -r requirements.txt"
]

[phases.start]
commands = [
  "python app.py"  # Substitua "app.py" pelo nome do arquivo principal se for diferente
]

[environment]
PYTHON_VERSION = "3.10"
